# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_image', models.ImageField(upload_to='')),
                ('grid_title', models.CharField(max_length=100)),
                ('grid_detail', models.CharField(max_length=100)),
                ('modal_title', models.CharField(max_length=100)),
                ('modal_subtitle', models.CharField(max_length=100)),
                ('modal_image', models.ImageField(upload_to='')),
                ('modal_detail', models.TextField()),
            ],
        ),
    ]
